# ناوی ئەو فایلەی دروست دەبێت
TWEAK_NAME = M1StoreWelcome

# ناوی ئەو فایلانەی کۆدیان تێدایە (ئەوەی پێشتر دروستت کرد)
M1StoreWelcome_FILES = Tweak.x

# ئەو فریمۆرکەی بۆ دایەلۆگ پێویستە
M1StoreWelcome_FRAMEWORKS = UIKit

# ڕێکخستنی جۆری پڕۆسێسەر (بۆ ئایفۆنە نوێیەکان)
ARCHS = arm64 arm64e

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
